site_name: lernOS für Dich Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Grundlagen:
        - Überblick: 1-0-Grundlagen.md
        - Wissensarbeit und Lebenslanges Lernen: 1-1-Lebenslanges-Lernen-und-Wissensarbeit.md
        - lernOS Canvas: 1-2-lernOS-Canvas.md
        - lernOS Flow: 1-3-lernOS-Flow.md
        - lernOS Workplace: 1-4-lernOS-Workplace.md
        - lernOS Memex: 1-5-lernOS-Memex.md
    - Lernpfade:
        - Überblick: 2-0-Lernpfade.md
        - Lernpfad Produktivität & Stressfreiheit:
            - Überblick: 2-1-0-Lernpfad-PS.md
            - Top 10 Quellen zu GTD (Kata): 2-1-1-Kata-1.md
            - Zeug sammeln und Mind sweepen (Kata): 2-1-2-Kata-2.md
            - Richte deine GTD-Umgebung ein (Kata): 2-1-3-Kata-3.md
            - Welche Inbox(en) willst du verwenden? (Kata): 2-1-4-Kata-4.md
            - Welche Listen willst du anlegen und führen? (Kata): 2-1-5-Kata-5.md
            - Inbox Zero in 4 Schritten (Kata): 2-1-6-Kata-6.md
            - Richte deine Projektumgebung ein (Kata): 2-1-7-Kata-7.md
            - Lege deine Referenzablage an (Kata): 2-1-8-Kata-8.md
            - Mache ein Weekly Review (Kata): 2-1-9-Kata-9.md
            - Mache ein Daily Review (Kata): 2-1-10-Kata-10.md
            - Die 6 Fokushorizonte von Getting Things Done (Kata): 2-1-11-Kata-11.md
        - Lernpfad Zielorientierung & Fokussierung:
            - Überblick: 2-2-0-Lernpfad-ZF.md
            - Top 10 Quellen zu OKRs (Kata): 2-2-1-Kata-1.md
            - Richte deine OKR-Umgebung ein (Kata): 2-2-2-Kata-2.md
            - Definiere OKRs für deinen Sprint (Kata): 2-2-3-Kata-3.md
            - Finalisiere deine OKRs für den Sprint (Kata): 2-2-4-Kata-4.md
            - Führe dein Weekly Check-In durch (Kata): 2-2-5-Kata-5.md
            - Tools für OKRs (Kata): 2-2-6-Kata-6.md
            - Scoring vs. Measuring Key Results (Kata): 2-2-7-Kata-7.md
            - Stretch Goals and Moonshots (Kata): 2-2-8-Kata-8.md
            - What is your Confidence Level? (Kata): 2-2-9-Kata-9.md
            - Individual vs. Team/Organizational OKRs (Kata): 2-2-10-Kata-10.md
            - OKR Review (Kata): 2-2-11-Kata-11.md
        - Lernpfad Offenheit & Vernetzung:
            - Überblick: 2-3-0-Lernpfad-OV.md
            - Wähle ein geeignetes Ziel für den Lernpfad (Kata): 2-3-1-Kata-1.md
            - Gestalte deine WOL Umgebung (Kata): 2-3-2-Kata-2.md
            - Teile etwas mit dem Netzwerk (Kata): 2-3-3-Kata-3.md
            - Mache Termine mit dir selbst (Kata): 2-3-4-Kata-4.md
            - Beschreibe dich in 25 Tags (Kata): 2-3-5-Kata-5.md
            - Aktualisiere deinen digitalen Zwilling (Kata): 2-3-6-Kata-6.md
            - Erweitere deine WOL Umgebung (Kata): 2-3-7-Kata-7.md
            - Poste deine Top 10 Trüffel (Kata): 2-3-8-Kata-8.md
            - Welche Kanäle willst du nutzen? (Kata): 2-3-9-Kata-9.md
            - Welche Communities können dir helfen? (Kata): 2-3-10-Kata-10.md
            - Schreibe einen Brief an dein zukünftiges Ich (Kata): 2-3-11-Kata-11.md
    - Anhang: 3-Anhang.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-fuer-Dich-Leitfaden.pdf
      - Word-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-fuer-Dich-Leitfaden.docx
      - HTML-Version: https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-fuer-Dich-Leitfaden.html
      - E-Book (epub): https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-fuer-Dich-Leitfaden.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-for-you/blob/master/de/lernOS-fuer-Dich-Leitfaden.mobi
    - Links:
      - lernos.org: https://lernos.org
      - lernOS Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-for-you'
repo_url: 'https://github.com/cogneon/lernos-for-you'

extra:
    homepage: https://lernos.org
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    analytics:
        provider: custom
    generator: false

    markdown_extensions:
      - pymdownx.superfences:
          custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

    plugins:
      - search
      - mermaid2
